
name: CI - Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Pushes to github pages repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        REACT_APP_BACKEND_API: ${{ secrets.REACT_APP_BACKEND_API }}
      with:
        source-directory: 'build'
        destination-github-username: 'spreadyourlinks'
        destination-repository-name: 'spreadyourlinks.github.io'
        user-email: me@iamdhrumilshah.com
        target-branch: gitcopy
