name: CI - Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: npm install
      run: 'npm install'

    - name: Build
      run: 'npm run build'
      env:
        REACT_APP_BACKEND_API: ${{ secrets.REACT_APP_BACKEND_API }}
        REACT_APP_GA_ID: ${{ secrets.REACT_APP_GA_ID }}
        REACT_APP_GTM_ID: ${{ secrets.REACT_APP_GTM_ID }}

    - name: Pushes to github pages repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'build'
        destination-github-username: 'spreadyourlinks'
        destination-repository-name: 'spreadyourlinks.github.io'
        user-email: spreadyourlinks@iamdhrumilshah.com
        target-branch: gitcopy
